import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const compiledAppsDir = join(rootDir, "dist", "apps");
const packagesDir = join(rootDir, "dist", "packages");
const envFileName = process.env.BUILD_ENV_FILE ?? ".env";
const envFilePath = existsSync(join(rootDir, envFileName))
  ? join(rootDir, envFileName)
  : join(rootDir, ".env.example");
const env = loadEnv(envFilePath);
const commit = readGitValue(["rev-parse", "--short", "HEAD"]) ?? "unknown";
const builtAt = new Date().toISOString();

const services = [
  {
    name: "coordinator",
    title: "TryOnService Coordinator",
    entry: "app/apps/coordinator/index.js",
    directories: ["coordinator", "shared"],
    envKeys: [
      "COORDINATOR_PORT",
      "COORDINATOR_PUBLIC_URL",
      "WORKER_REGISTRATION_KEY",
      "WORKER_REGISTRATION_MAX_INVALID_ATTEMPTS",
      "CLIENT_REGISTRATION_KEY",
      "WORKER_HEARTBEAT_INTERVAL_MS",
      "WORKER_HEARTBEAT_TIMEOUT_MS",
      "CLIENT_HEARTBEAT_INTERVAL_MS",
      "CLIENT_HEARTBEAT_TIMEOUT_MS",
      "SCHEDULER_INTERVAL_MS",
      "WORKER_DISPATCH_TOKEN_TTL_MS",
      "JOB_ASSIGNMENT_TIMEOUT_MS",
    ],
  },
  {
    name: "worker",
    title: "TryOnService Worker",
    entry: "app/apps/worker/index.js",
    directories: ["worker", "shared"],
    envKeys: [
      "WORKER_PORT",
      "WORKER_ID",
      "WORKER_PUBLIC_PROTOCOL",
      "WORKER_PUBLIC_URL",
      "WORKER_CAPACITY",
      "WORKER_CAPABILITIES",
      "WORKER_HEARTBEAT_INTERVAL_MS",
      "MOCK_PROCESSING_DELAY_MS",
      "COORDINATOR_URL",
      "WORKER_REGISTRATION_KEY",
    ],
  },
  {
    name: "telegram-client",
    title: "TryOnService Telegram Client",
    entry: "app/apps/client/telegram/index.js",
    directories: ["client", "shared"],
    envKeys: [
      "TELEGRAM_CLIENT_ID",
      "TELEGRAM_CLIENT_PORT",
      "TELEGRAM_CLIENT_PUBLIC_PROTOCOL",
      "TELEGRAM_CLIENT_PUBLIC_URL",
      "TELEGRAM_BOT_TOKEN",
      "TELEGRAM_POLLING_TIMEOUT_SECONDS",
      "COORDINATOR_URL",
      "CLIENT_REGISTRATION_KEY",
      "CLIENT_HEARTBEAT_INTERVAL_MS",
    ],
  },
];

if (!existsSync(compiledAppsDir)) {
  throw new Error("Compiled apps were not found. Run npm run build before packaging.");
}

rmSync(packagesDir, { recursive: true, force: true });
mkdirSync(packagesDir, { recursive: true });

for (const service of services) {
  writeServicePackage(service);
}

console.log(`[build-dist] Built deploy packages from ${envFileName}:`);

for (const service of services) {
  console.log(`- dist/packages/${service.name}`);
}

function writeServicePackage(service) {
  const packageDir = join(packagesDir, service.name);
  const appDir = join(packageDir, "app", "apps");

  mkdirSync(appDir, { recursive: true });

  for (const directory of service.directories) {
    cpSync(join(compiledAppsDir, directory), join(appDir, directory), {
      recursive: true,
    });
  }

  writeFileSync(
    join(packageDir, "package.json"),
    `${JSON.stringify(
      {
        name: `try-on-service-${service.name}`,
        version: "0.1.0",
        private: true,
        type: "module",
        scripts: {
          start: `node ${service.entry}`,
        },
        engines: {
          node: ">=18",
        },
      },
      null,
      2,
    )}\n`,
  );

  writeFileSync(join(packageDir, ".env"), buildEnvFile(service.envKeys));
  writeFileSync(join(packageDir, "start.cmd"), buildWindowsStart(service.entry));
  writeFileSync(join(packageDir, "start.sh"), buildUnixStart(service.entry));
  writeFileSync(join(packageDir, "README.md"), buildPackageReadme(service));
  writeFileSync(
    join(packageDir, "BUILD_INFO.txt"),
    `service=${service.name}\ncommit=${commit}\nbuiltAt=${builtAt}\nsourceEnv=${envFileName}\n`,
  );
}

function buildEnvFile(keys) {
  return `${keys
    .map((key) => `${key}=${env[key] ?? ""}`)
    .join("\n")}\n`;
}

function buildWindowsStart(entry) {
  return `@echo off\r\ncd /d "%~dp0"\r\nnode ${entry}\r\n`;
}

function buildUnixStart(entry) {
  return `#!/usr/bin/env sh\ncd "$(dirname "$0")"\nnode ${entry}\n`;
}

function buildPackageReadme(service) {
  return `# ${service.title}

This folder is a ready-to-run deploy package generated by \`npm run build:dist\`.

## Run

Windows:

\`\`\`cmd
start.cmd
\`\`\`

Linux/macOS:

\`\`\`bash
sh start.sh
\`\`\`

Or with npm:

\`\`\`bash
npm start
\`\`\`

## Configuration

Runtime settings are stored in \`.env\` in this package. The file was generated from \`${envFileName}\` during build.

Entry point: \`${service.entry}\`
`;
}

function loadEnv(filePath) {
  const result = {};

  if (!existsSync(filePath)) {
    return result;
  }

  const lines = readFileSync(filePath, "utf8").split(/\r?\n/);

  for (const line of lines) {
    const parsed = parseEnvLine(line);

    if (!parsed) {
      continue;
    }

    result[parsed.key] = process.env[parsed.key] ?? parsed.value;
  }

  return result;
}

function parseEnvLine(line) {
  const trimmed = line.trim();

  if (!trimmed || trimmed.startsWith("#")) {
    return undefined;
  }

  const separatorIndex = trimmed.indexOf("=");

  if (separatorIndex <= 0) {
    return undefined;
  }

  const key = trimmed.slice(0, separatorIndex).trim();
  const value = unquote(trimmed.slice(separatorIndex + 1).trim());

  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
    return undefined;
  }

  return { key, value };
}

function unquote(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }

  return value;
}

function readGitValue(args) {
  try {
    return execFileSync("git", args, {
      cwd: rootDir,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return undefined;
  }
}
